version: '3.1'

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app

  
  # mongodb_container:
  #   # This image automatically creates a replica set required for transactions
  #   image: prismagraphql/mongo-single-replica:4.4.3-bionic
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: prisma
  #     INIT_WAIT_SEC: 5
  #   ports:
  #     - 27017:27017

  # mongo:
  #   build: ./mongo_replica
  #   restart: always
  #   container_name: poc-mongo
  #   command: --replSet rs0
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: prisma
  #     MONGODB_INITDB_DATABASE: mongo
  #     MONGO_REPLICA_HOST: host.docker.internal
  #     MONGO_REPLICA_PORT: 27017
  #   ports:
  #     - '27017:27017'

  db:
    image: 'bitnami/mongodb:latest'
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    environment:
      MONGO_ROOT_PASSWORD: root
      # MONGODB_REPLICA_SET_MODE: primary
      # MONGODB_REPLICA_SET_KEY: 123456Ald
      MONGODB_DATABASE: nest
    ports:
      - '27017:27017'


  # mongodb_migrate:
  #   image: mongo:4
  #   restart: unless-stopped
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: prisma
  #     MONGO_INITDB_DATABASE: tests-migrate
  #   ports:
  #     - '27017:27017'

  # mongodb_migrate_seed:
  #   build: ./mongodb_migrate_seed
  #   depends_on:
  #     - mongodb_migrate

  mongo:
    build: ./mongodb_replica
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_REPLICA_HOST: host.docker.internal
      MONGO_REPLICA_PORT: 27018
    ports:
      - '27018:27018'

# volumes:
#   db_data:

volumes:
  mongodb_data:
    driver: local
